image: jacekmarchwicki/android
before_script:
  - export ANDROID_HOME="/opt/android-sdk"

debug-app:
    script:
    - ./gradlew assembleDebug

    artifacts:
        paths:
        - app/build/outputs/apk/app-debug.apk